config/routes.rb
Rails.application.routes.draw do
  get 'citas', to: 'public_meet#new', as: 'public_meet'
  post 'citas/create', to: 'public_meet#create_meet', as: 'create_meet'

  get 'public_posts/index'
  get 'articulos/:url', to: 'public_posts#show', as: 'public_post'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'

  root 'public_posts#index'

  devise_for :users

  resources :meets

  resources :ads

  resources :comments
  post 'comments/create', to: 'public_posts#create_comment', as: 'create_comment_post'

  resources :categories

  resources :posts
  get 'admin', to: 'posts#index', as: 'admin_post'

end

app/models/meet.rb
class Meet < ActiveRecord::Base

end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meet, only: [:show, :edit, :update, :destroy]

  # GET /meets
  # GET /meets.json
  def index
    @meets = Meet.all
  end

  # GET /meets/1
  # GET /meets/1.json
  def show
  end

  # GET /meets/new
  def new
    @meet = Meet.new
  end

  # GET /meets/1/edit
  def edit
  end

  # POST /meets
  # POST /meets.json
  def create
    @meet = Meet.new(meet_params)

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: 'Meet was successfully created.' }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meets/1
  # PATCH/PUT /meets/1.json
  def update
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to @meet, notice: 'Meet was successfully updated.' }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1
  # DELETE /meets/1.json
  def destroy
    @meet.destroy
    respond_to do |format|
      format.html { redirect_to meets_url, notice: 'Meet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meet
      @meet = Meet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meet_params
      params.require(:meet).permit(:subject, :meeting, :status, :name)
    end
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/meets/_form.html.erb
<%= form_for(@meet) do |f| %>
  <% if @meet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
      <% @meet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Asunto' %><br>
    <%= f.text_area :subject %>
  </div>
  <div class="field">
    <%= f.label 'Fecha' %><br>
    <%= f.date_select :meeting %>
  </div>
  <div class="field">
    <%= f.label 'Confirmada' %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label 'Nombre solicitante' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meets/edit.html.erb
<h1>Editar Cita</h1>

<%= render 'form' %>

<%= link_to 'Show', @meet %> |
<%= link_to 'Back', meets_path %>

app/views/meets/index.html.erb
<h1>Citas</h1>

<table class="table table-default">
  <thead>
    <tr>
      <th>Asunto</th>
      <th>Fecha</th>
      <th>Confirmada</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meets.each do |meet| %>
      <tr>
        <td><%= meet.subject %></td>
        <td><%= meet.meeting %></td>
        <td><%= meet.status %></td>
        <td><%= meet.name %></td>
        <td><%= link_to 'Ver', meet %></td>
        <td><%= link_to 'Editar', edit_meet_path(meet) %></td>
        <td><%= link_to 'Eliminar', meet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Cita', new_meet_path, class: 'btn btn-default' %>

app/views/meets/new.html.erb
<h1>Crear Cita</h1>

<%= render 'form' %>

<%= link_to 'Atras', meets_path %>

app/views/meets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @meet.subject %>
</p>

<p>
  <strong>Meeting:</strong>
  <%= @meet.meeting %>
</p>

<p>
  <strong>Status:</strong>
  <%= @meet.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @meet.name %>
</p>

<%= link_to 'Edit', edit_meet_path(@meet) %> |
<%= link_to 'Back', meets_path %>