config/routes.rb
Rails.application.routes.draw do
  get 'citas', to: 'public_meet#new', as: 'public_meet'
  post 'citas/create', to: 'public_meet#create_meet', as: 'create_meet'

  get 'public_posts/index'
  get 'articulos/:url', to: 'public_posts#show', as: 'public_post'
  get 'categorias/:id', to: 'public_posts#posts_category', as: 'posts_category'

  root 'public_posts#index'

  devise_for :users

  resources :meets

  resources :ads

  resources :comments
  post 'comments/create', to: 'public_posts#create_comment', as: 'create_comment_post'

  resources :categories

  resources :posts
  get 'admin', to: 'posts#index', as: 'admin_post'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_and_belongs_to_many :categories
  belongs_to :user
  has_many :post_edits

  scope :published, -> { where(status: true)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :categories_public, only: [:edit, :new, :create, :update]
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_edits = @post.post_edits
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    #@post.categories = params[:post][:categories]

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :status, :content, :user_id, category_ids: [])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label 'Titulo' %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label "Categoría" %><br>
    <%#= f.select :category_ids, @list_categories.collect {|c| [c.name, c.id]}, {include_blank: false}, {:multiple => true, class: 'form-control'} %>
    <%= f.collection_select :category_ids, @list_categories, :id, :name, {}, {multiple: true, class: 'form-control'} %>
  </div>
  <div class="field">
    <%= f.label 'Publicada' %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label 'Contenido' %><br>
    <%= f.text_area :content, class: 'form-control ckeditor' %>
  </div>
  <div class="actions">
    <%= f.submit 'Crear', class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editar Articulo</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Articulos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Titulos</th>
      <th>Dirección</th>
      <th>Categoria</th>
      <th>Publicado</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.categories.collect { |c| c.name }%></td>
        <td><%= post.status %></td>

        <td><%= link_to 'Vista Previa', public_post_path(post.url), class: 'btn btn-default' %></td>
        <td>
          <%= link_to 'Ver', post, class: 'btn btn-default' %>
          <%= link_to 'Editar', edit_post_path(post), class: 'btn btn-default' %>
          <%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear Artículo', new_post_path, class: 'btn btn-default' %>

app/views/posts/new.html.erb
<h1>Crear articulo</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.categories.collect { |c| c.name } %>
</p>

<p>
  <strong>Status:</strong>
  <%= @post.status %>
</p>

<p>
  <strong>Content:</strong>
  <%== @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<hr/>

<h3>Historial de ediciones</h3>
<% @post_edits.each do |p| %>
    <small><b><%= p.editor.email %></b> editó el <b><%= p.created_at %></b></small> <br/>
<% end %>